### ISSUE TITLE
Prefer using interfaces from the Aptos SDK

### ISSUE THREAD

**Issue by 0xPrimata** [ThalaLabs/surf#112]
For the sake of maintainability, it would be preferrable to use interfaces provided by the Aptos SDK. One example is the interface ABIRoot constructed locally:

```
export interface ABIRoot {
  address: string;
  name: string;
  friends: readonly string[];
  exposed_functions: readonly ABIFunction[];
  structs: readonly ABIStruct[];
}
```

It matches MoveModule that could come to Aptos:
```
type MoveModule = {
    address: string;
    name: string;
    /**
     * Friends of the module
     */
    friends: Array<MoveModuleId>;
    /**
     * Public functions of the module
     */
    exposed_functions: Array<MoveFunction>;
    /**
     * Structs of the module
     */
    structs: Array<MoveStruct>;
};
```

Using Client methods return Aptos types and they end up requiring casting. I believe it ends up curving maintainability and upstream compatibility. Would be glad to understand if there's a reason behind local types.

**Comment by SamuelQZQ** [comment]
@0xPrimata good point! We will try to see if it works.
