### ISSUE TITLE
How to use surf with wallet adaptor?

### ISSUE THREAD

**Issue by 0xaptosj** [ThalaLabs/surf#125]
I'm using surf in all my projects now. But one thing i didn't figure out is how to use it with wallet adaptor. Take this code as an example

```ts
import { useWallet } from "@aptos-labs/wallet-adapter-react";
export const MyComponent = () => {
  const { account, signAndSubmitTransaction } = useWallet();
  const response = await signAndSubmitTransaction({
    sender: account.address,
    data: {
      function: `${ABI.address}::my_contract::my_function`,
      typeArguments: [],
      functionArguments: [],
    },
  });
  await aptosClient.waitForTransaction({
    transactionHash: response.hash,
  });
}
```

If I want to use surf, I would write 
```ts
import { useWallet } from "@aptos-labs/wallet-adapter-react";
export const MyComponent = () => {
  const { account, signAndSubmitTransaction } = useWallet();
  const response = await surfClient.entry.my_function({
      typeArguments: [],
      functionArguments: [],
      account,
    });
}
```

But since `account` comes from wallet adaptor instead of created with private key, I got account missing privateKey error.

**Comment by SamuelQZQ** [comment]
@0xaptosj  see this example: https://github.com/ThalaLabs/surf/blob/main/example/app/page.tsx

Basically you can import these things:
`import { useSubmitTransaction, useWalletClient } from '@thalalabs/surf/hooks';`

Those hooks are some wrapper around the adapter.

**Comment by 0xaptosj** [comment]
> some

Ah nice, this is amazing!
