### ISSUE TITLE
Consider publishing package to npmjs again

### ISSUE THREAD

**Issue by banool** [ThalaLabs/surf#138]
In https://github.com/ThalaLabs/surf/issues/73 @SamuelQZQ mentioned that you publish the package to GH rather than npmjs for security reasons. Could you explain what the security concerns are with npmjs? It is simpler for devs to just install from npmjs. Indeed, we consider npmjs acceptable from a security perspective for all our packages (though if there is something we're not thinking of please let us know!).

**Comment by SamuelQZQ** [comment]
@banool We agree with you, have switched back to the npm registry.
