### ISSUE TITLE
Getting unknown for Object and Option type

### ISSUE THREAD

**Issue by 0xaptosj** [ThalaLabs/surf#155]
## For Object type

`get_messages` returns a vector of objects with type being `my_module_address::Message`, however the type inferred by surf is `unknown[]`, I was expecting it to return `{inner: string}[]`.

[Node script using surf](https://github.com/aptos-labs/move-by-examples/blob/5ecb373938b3ba15a0d65ade2eb67659d4032150/surf-for-type-safety/apps/node_script/src/get_messages.ts).

[Contract code](https://github.com/aptos-labs/move-by-examples/blob/5ecb373938b3ba15a0d65ade2eb67659d4032150/surf-for-type-safety/contracts/message-board/sources/message_board.move#L88)

<img width="832" alt="Screenshot 2024-07-05 at 11 10 44 AM" src="https://github.com/ThalaLabs/surf/assets/129789810/a75edc4a-f658-4a85-a716-ae5294cb4017">

## For Option type

`get_message_content` returns all fields of the message, where it has a bunch of fields with `Option` type. Surf also returns `unknown` for those `Option` types.

[Node script using surf](https://github.com/aptos-labs/move-by-examples/blob/5ecb373938b3ba15a0d65ade2eb67659d4032150/surf-for-type-safety/apps/node_script/src/get_message_content.ts#L7)

[Contract code](https://github.com/aptos-labs/move-by-examples/blob/5ecb373938b3ba15a0d65ade2eb67659d4032150/surf-for-type-safety/contracts/message-board/sources/message_board.move#L116)

<img width="782" alt="Screenshot 2024-07-05 at 11 14 57 AM" src="https://github.com/ThalaLabs/surf/assets/129789810/8eb74e08-ce2d-46f6-9eef-98a491eafdc1">

**Comment by 0xbe1** [comment]
@0xaptosj can you elaborate?

**Comment by 0xaptosj** [comment]
> @0xaptosj can you elaborate?

Yes, I will add more detail this week, i'm working a in depth tutorial on surf now and will have an update soon

**Comment by SamuelQZQ** [comment]
@0xaptosj thank you for the information. I will try to fix it.

**Comment by SamuelQZQ** [comment]
@0xaptosj should be fixed in @thalalabs/surf@1.7.2
