### ISSUE TITLE
Triggered error `a value of struct type: ${arg} is not supported` when passing null

### ISSUE THREAD

**Issue by 0xaptosj** [ThalaLabs/surf#161]
I have a function that takes optional value as parameters. When I pass null (surf requires passing `null` as `option::none()` to pass type check, but aptos ts-sdk typically uses `undefined` as `option::none()`, I triggered error at this [line](https://github.com/ThalaLabs/surf/blob/3815bcf024438026f7dce87cd4971f3698768374/src/core/WalletClient.ts#L32).

My full code: https://github.com/aptos-labs/move-by-examples/blob/j/surf/surf-for-type-safety/apps/web/src/components/transactionFlows/PostMessageWithSurf.tsx#L24-L38

Entry function i'm calling: https://github.com/aptos-labs/move-by-examples/blob/j/surf/surf-for-type-safety/contracts/message-board/sources/message_board.move#L39-L47

**Comment by 0xaptosj** [comment]
My guess is if we switch from `null` to `undefined` in surf, the issue will be gone. But that's probably a breaking change for surf users

**Comment by SamuelQZQ** [comment]
Got it. Thank you! Will fix it. 
Does this workaround could work for you temporarily:
```
{
  functionAguments: [undefined as any]
}
```

**Comment by SamuelQZQ** [comment]
@0xaptosj should be fixed in 1.7.0
