### ISSUE TITLE
support Object<T> as both input args and return type

### ISSUE THREAD

**Issue by 0xbe1** [ThalaLabs/surf#2]
See https://explorer.aptoslabs.com/account/0x1/modules/code/fungible_asset?network=devnet as an example that uses Object in many different places.

Regarding object serde, probably need to check aptos-core codebase to understand what's the expected behavior.

**Comment by SamuelQZQ** [comment]
@0xbe1 We have support Object as input. Haven't tried any view function or account resource including Object type, we can update that when figured it out.
