### ISSUE TITLE
How to use types in functions?

### ISSUE THREAD

**Issue by banool** [ThalaLabs/surf#67]
Hey hey,

Let's say I have a Move module with a Board struct in it. I want to write a function in my frontend that takes in a Board as an argument. Is this possible with Surf? I suspect not since there is no actual codegen but I'm asking just in case.

Thanks!

**Comment by banool** [comment]
Yeah probably easier to use a concrete example. I'm currently building chess on Aptos in my spare time. You can see I have a variety of structs in the module here: https://github.com/banool/aptos-chess/blob/main/move/sources/chess.move#L90.

I want to write many different functions that let me read these resources in a type safe way. For example, something like:
```
function boardToFen(board: Board): string {
    // todo
}
```

This is FEN btw: https://www.chess.com/terms/fen-chess.

**Comment by SamuelQZQ** [comment]
@banool If you want to read a resource, you can do like this:
```
const { data } = await client.useABI(COIN_ABI).resource.CoinStore({
  type_arguments: ['0x1::aptos_coin::AptosCoin'],
  account: '0x1',
});

// Get property in the struct with type safety
console.log(data.frozen);

// It also works for nested struct type.
// The `coin` property's type is 0x1::coin::Coin<T0>
console.log(data.coin.value);
```

**Comment by 0xbe1** [comment]
@banool in your case, you can do

```
const { data } = await client.useABI(CHESS_ABI).resource.Game({ account: "0x..." });
const board = data.board; // this is a type-safe Board
```

**Comment by banool** [comment]
That's not the issue, the issue is once I have that resource I can't work with it in a type safe way in other functions easily:
```
const { game } = await client.useABI(CHESS_ABI).resource.Game({
  type_arguments: [],
  account: '0x123',
});

const getFen = boardToFen(game.board);
```

There is no way for me to declare in `boardToFen` what type I'm dealing with.

**Comment by SamuelQZQ** [comment]
@banool We can provide a util type function to help with that: `StructType<ABITable, ABI, StructName>`. What do you think? We can add it tomorrow.

**Comment by banool** [comment]
I think that'd be helpful but just to make sure, could you add an example demonstrating how you'd use it with my `boardToFen` function above?

**Comment by SamuelQZQ** [comment]
@banool Ideally, after we add the new util type function, you can declare the function like this:
```
import { DefaultABITable } from "@thalalabs/surf/build/types/types";

function boardToFen(arg: StructType<DefaultABITable, CHESS_ABI, "Board"> ) {

}
```

**Comment by banool** [comment]
Neat that looks good to me!

**Comment by SamuelQZQ** [comment]
@banool Try the newest version, you can do like this:

```TypeScript
import { DefaultABITable, ExtractStructType } from "@thalalabs/surf";
type ABITAble = DefaultABITable & {
  "your_contract_address::Chess": typeof CHESS_ABI;
};

type Board = ExtractStructType<ABITAble, typeof CHESS_ABI, "Board">

// or
type Game = ExtractStructType<ABITAble, typeof CHESS_ABI, "Game">
type Board = Game['board']
```

In IDE, those string could be get through auto-completion.

**Comment by banool** [comment]
Awesome it works a treat.

One thing I notice is if you don't have the right module ID the type inference still proceeds but it misses a lot of information. 

For example, this gives me rich type information:
```
type ABITAble = DefaultABITable & {
  "0x296102a3893d43e11de2aa142fbb126377120d7d71c246a2f95d5b4f3ba16b30::chess": typeof CHESS_ABI;
};
```

But this doesn't:
```
type ABITAble = DefaultABITable & {
  "0x296102a3893d43e11de2aa142fbb126377120d7d71c246a2f95d5b4f3ba16b30::Chess": typeof CHESS_ABI;
};
```

I would rather the second case be an error rather than it just degrade silently.

**Comment by SamuelQZQ** [comment]
https://github.com/ThalaLabs/surf/pull/70
